project/web_app/mod_landing/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo, Required


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    accept_conditions = BooleanField('Accept Conditions')
    submit = SubmitField('Register')


class ForgotForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Reset')


# class LoginForm(FlaskForm):
#     email = TextField('Email Address', [Email(), Required(message='Forgot your email address?')])
#     password = PasswordField('Password', [Required(message='Must provide a password. ;-)')])

project/web_app/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask, render_template
from flask_restful import reqparse, abort, Api, Resource
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy


# Define the WSGI application object
app = Flask(__name__)
cors = CORS(app, resources={r"*": {"origins": "*"}})
api = Api(app)

# Define the database object which is imported by modules and controllers
db = SQLAlchemy(app)

# Configurations
app.config.from_object('config')


# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('errors/404.html'), 404


# Import a module / component using its blueprint handler variable
# Importing landing modules

from project.web_app.mod_start.views import module_start as start_module
from project.web_app.mod_landing.views import module_landing as landing_module

# Importing administration modules
from project.web_app.mod_auth.views import module_authorization as auth_module
from project.web_app.mod_admin.views import module_administration as admin_module
from project.web_app.mod_projects.views import module_projects as projects_module
from project.web_app.mod_analytics.views import module_analytics as analytics_module

# Importing components modules
from project.web_app.mod_files.views import module_files as files_module
from project.web_app.mod_email.views import module_email as email_module


# Register blueprint(s)
app.register_blueprint(start_module)
app.register_blueprint(landing_module)
app.register_blueprint(auth_module)
app.register_blueprint(admin_module)
app.register_blueprint(projects_module)
app.register_blueprint(analytics_module)
app.register_blueprint(files_module)
app.register_blueprint(email_module)


# Build the database
db.create_all()

project/web_app/mod_analytics/views.py
# -*- coding: utf-8 -*-
# Standard library imports
import os
import glob

# Third party imports
from flask import Flask, g, Blueprint, render_template, flash, session, redirect, url_for, request, send_from_directory, \
    send_file, jsonify
from bokeh.core.properties import value
from bokeh.models import (HoverTool, FactorRange, Plot, LinearAxis, Grid, Range1d)
from bokeh.models.glyphs import VBar
from bokeh.plotting import Figure, show, output_file
from bokeh.embed import components
from bokeh.models.sources import ColumnDataSource
import numpy as np
import pandas as pd

# Local application imports
import project.web_app.analytics.comparator as comp

# Define the blueprint: 'start', set its url prefix: app.url/start
module_analytics = Blueprint('analytics', __name__, url_prefix='/analytics')


''' Definiciones de ANALYTICS'''


@module_analytics.route('/comparator', methods=['GET'])
def comparator():
    def tabs(item):
        if item is '\t':
            return False
        else:
            return True

    def spaces(item):
        if item is '\n':
            return False
        else:
            return True

    list_of_files = glob.glob("../project/documents/compared/*")
    latest_file = max(list_of_files, key=os.path.getctime)
    list_of_kb_files = glob.glob("../project/documents/knowledge_base/*")

    whole_base_paragraphs_list = []

    for kb_file in list_of_kb_files:
        base_paragraphs_list = comp.get_word_paragraphs(kb_file)
        whole_base_paragraphs_list.extend(base_paragraphs_list)


    base_document = list(filter(None, whole_base_paragraphs_list))

    query_paragraphs_list = comp.get_word_paragraphs(latest_file)
    query_document_one = list(filter(None, query_paragraphs_list))
    query_document_two = list(filter(tabs, query_document_one))
    query_document_three = list(filter(spaces, query_document_two))

    paragraphs = comp.compare_documents(base_document, query_document_three)
    return render_template('analytics/table.html', paragraphs=paragraphs)


#
#
#
# @module_start.route('/paquetes_movistar', methods=['GET'])
# def paquetes_movistar():
#     table = movistar_paquetes.get_plans()
#     return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes Movistar")
#
#
# @module_start.route('/paquetes_tigo', methods=['GET'])
# def paquetes_tigo():
#     table = tigo_paquetes.get_plans()
#     return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes TIGOUNE")
#
#
# @module_start.route('/pospago_claro', methods=['GET'])
# def pospago_claro():
#     table = claro_pospago.get_plans()
#     return render_template('dashboard/pospago.html', table=table, section_title="Pospago Claro")
#
#
# @module_start.route('/pospago_movistar', methods=['GET'])
# def pospago_movistar():
#     table = movistar_pospago.get_plans()
#     return render_template('dashboard/pospago.html', table=table, section_title="Pospago Movistar")
#
#
# @module_start.route('/celulares_tigo', methods=['GET'])
# def celulares_tigo():
#     table = tigo_celulares.get_cellphones()
#     return render_template('dashboard/celulares.html', table=table, section_title="Celulares TIGOUNE")
#
#
# @module_start.route('/download_data/<file>', methods=['GET'])
# def download_data(file):
#     try:
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../Magnet/analytics/data"))
#         file_path = glob.glob(data_directory + '/**/' + '{}.csv'.format(file), recursive=True)
#         return send_file(file_path[0], attachment_filename="{}.csv".format(file), as_attachment=True)
#     except Exception as e:
#         return str(e)
#
#
# @module_start.route('/data/api/v1.0/<tipo>/<operador>', methods=['GET'])
# def get_data(tipo, operador):
#     if tipo == "planes" and operador == "claro":
#         list = claro_pospago.get_plans()
#         return jsonify(results=list)
#     elif tipo == "planes" and operador == "movistar":
#         list = movistar_pospago.get_plans()
#         return jsonify(results=list)
#     elif tipo == "paquetes" and operador == "claro":
#         list = claro_paquetes.get_plans()
#         return jsonify(results=list)
#     elif tipo == "paquetes" and operador == "movistar":
#         list = movistar_paquetes.get_plans()
#         return jsonify(results=list)
#     elif tipo == "paquetes" and operador == "tigo":
#         list = tigo_paquetes.get_plans()
#         return jsonify(results=list)
#     elif tipo == "celulares" and operador == "tigo":
#         list = tigo_celulares.get_cellphones()
#         return jsonify(results=list)
#     else:
#         return jsonify(results="Sin Resultados")
#
#
# @module_start.route('/dashboard', methods=['GET'])
# def get_dashboard():
#     # p = Figure(title='Sine', x_axis_type="datetime", plot_width=1110, plot_height=400)
#     # x = np.linspace(-10, 10, 200)
#     # y = np.sin(x)
#     # p.line(x=x, y=y)
#     # script, div = components(p)
#
#     operadores = ['Claro', 'Movistar', 'Tigo-Une']
#     categorias = ["Voz", "Datos", "Voz y Datos"]
#     colors = ["#c9d9d3", "#718dbf", "#e84d60"]
#
#     data = {'operadores': operadores,
#             'Voz': [2, 1, 4],
#             'Datos': [5, 3, 4],
#             'Voz y Datos': [3, 2, 4]}
#
#     p = Figure(x_range=operadores, plot_width=1400, plot_height=250, title="Tipos de Planes x Operador",
#                toolbar_location=None, tools="hover", tooltips="$name @operadores: @$name")
#
#     p.vbar_stack(categorias, x='operadores', width=0.9, color=colors, source=data,
#                  legend=[value(x) for x in categorias])
#
#     script, div = components(p)
#
#     return render_template('dashboard/dashboard.html', script=script, div=div, section_title="Dashboard")

project/web_app/mod_email/views.py
# -*- coding: utf-8 -*-
# Standard library imports
from datetime import datetime

# Third party imports
from flask import Blueprint, flash, redirect, url_for

# Local application imports
import project.web_app.models as models
from project.web_app.mod_email.mod_email import email_sender
from .token import confirm_token


module_email = Blueprint('email', __name__, url_prefix='/email')


''' Definitions CONFIRM_EMAIL, SEND_EMAIL_TEST'''


@module_email.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('El link de confirmación ha expirado.', 'danger')
    user = models.User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Su cuenta es ya ha sido confirmada.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.now()
        models.db.session.add(user)
        models.db.session.commit()
        flash('¡Gracias! Has confirmado tu cuenta.', 'success')
    return redirect(url_for('auth.login'))


@module_email.route('/test/<email_address>')
def send_email_test(email_address):
    email = email_sender(email_address)
    return "We just send you a Message"

project/web_app/mod_files/views.py
# -*- coding: utf-8 -*-
# Standard library imports
import os, glob
import datetime

# Third party imports
from flask import Flask, g, Blueprint, render_template, flash, session, redirect, url_for, request, send_from_directory, \
    send_file
from flask_login import LoginManager
from flask_login import login_user, logout_user, current_user, login_required

from werkzeug.utils import secure_filename

from sqlalchemy import exc, func

# Local application imports
from project.web_app import app
import project.web_app.models as models
import project.web_app.mod_core.core as core


# Define the blueprint: 'files', set its url prefix: app.url/files
module_files = Blueprint('files', __name__, url_prefix='/files')


''' Definitions: FILES'''

UPLOAD_DATA_FOLDER = app.config['UPLOAD_DATA_FOLDER']
UPLOAD_REPORTS_FOLDER = app.config['UPLOAD_REPORTS_FOLDER']
ALLOWED_DOCUMENT_EXTENSIONS = set(['docx'])


@module_files.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    return render_template('files/files.html')


@module_files.route('/upload_document/', methods=['GET', 'POST'])
@login_required
def upload_document():
    data_directory = os.path.abspath(os.path.join(__file__, "../../documents/compared"))
    file = glob.glob(data_directory + '/**/' + '{}.docx'.format(datetime.datetime.now()), recursive=True)
    if request.method == 'POST':
        file = request.files['file']
        if file.filename == '':
            flash('Archivo no seleccionado')
            return redirect(url_for('files.upload_document'))
        else:
            file.filename = '{}.docx'.format(datetime.datetime.now())
            filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_DATA_FOLDER, filename))
            return redirect(url_for('analytics.comparator'))
    return render_template('files/upload_dataset.html', file=file)


# @module_files.route('/upload/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def upload(id_dataset):
#     context = core.get_dashboard_info()
#
#     return render_template('files/files.html', **context, id_dataset=id_dataset)
#
#
# @module_files.route('/download_data/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def download_data(id_dataset):
#     try:
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../files/data"))
#         file = glob.glob(data_directory + '/**/' + '{}.xlsx'.format(id_dataset), recursive=True)
#         dataset = models.Dataset.query.filter_by(dataset_id=id_dataset).first()
#         query = models.Query(user_id=current_user.id, dataset_id=id_dataset, query_type=2)
#         models.db.session.add(query)
#         models.db.session.commit()
#         return send_file(file[0], attachment_filename="{}.xlsx".format(dataset.title), as_attachment=True)
#     except Exception as e:
#         return str(e)
#
#
# @module_files.route('/upload_data/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def upload_data(id_dataset):
#     if current_user.admin is True:
#         context = core.get_dashboard_info()
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../files/data"))
#         file = glob.glob(data_directory + '/**/' + '{}.xlsx'.format(id_dataset), recursive=True)
#         if request.method == 'POST':
#             file = request.files['file']
#             if file.filename == '':
#                 flash('Archivo no seleccionado')
#                 return redirect(url_for('files.upload_data'))
#             else:
#                 file.filename = '{}.xlsx'.format(id_dataset)
#                 filename = secure_filename(file.filename)
#                 file.save(os.path.join(UPLOAD_DATA_FOLDER, filename))
#                 return redirect(url_for('admin.datasets'))
#         return render_template('files/upload_dataset.html', **context, file=file)
#     else:
#         return redirect(url_for('catalogue.catalogue_topics'))
#
#
# @module_files.route('/download_report/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def download_report(id_dataset):
#     try:
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../files/reports"))
#         file = glob.glob(data_directory + '/**/' + '{}.pdf'.format(id_dataset), recursive=True)
#         dataset = models.Dataset.query.filter_by(dataset_id=id_dataset).first()
#         query = models.Query(user_id=current_user.id, dataset_id=id_dataset, query_type=4)
#         models.db.session.add(query)
#         models.db.session.commit()
#         return send_file(file[0], attachment_filename="{}.pdf".format(dataset.title), as_attachment=True)
#     except Exception as e:
#         return str(e)
#
#
# @module_files.route('/upload_report/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def upload_report(id_dataset):
#     if current_user.admin is True:
#         context = core.get_dashboard_info()
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../files/reports"))
#         file = glob.glob(data_directory + '/**/' + '{}.pdf'.format(id_dataset), recursive=True)
#         if request.method == 'POST':
#             file = request.files['file']
#             if file.filename == '':
#                 flash('Archivo no seleccionado')
#                 return redirect(url_for('files.upload_data'))
#             else:
#                 file.filename = '{}.pdf'.format(id_dataset)
#                 filename = secure_filename(file.filename)
#                 file.save(os.path.join(UPLOAD_REPORTS_FOLDER, filename))
#                 return redirect(url_for('admin.datasets'))
#         return render_template('files/upload_report.html', **context, file=file)
#     else:
#         return redirect(url_for('catalogue.catalogue_topics'))
#
#
# @module_files.route('/visit/<id_dataset>', methods=['GET', 'POST'])
# @login_required
# def visit(id_dataset):
#     dataset = models.Dataset.query.filter_by(dataset_id=id_dataset).all()
#     hyperlink = dataset[0].hyperlink_url
#     query = models.Query(user_id=current_user.id, dataset_id=id_dataset, query_type=3)
#     models.db.session.add(query)
#     models.db.session.commit()
#     return redirect(url_for('catalogue.catalogue_topics', id_topic=dataset[0].topic_id))
#
#
# @module_files.route('/compare', methods=['GET', 'POST'])
# @login_required
# def compare():
#     #context = core.get_dashboard_info()
#
#     return render_template('files/files.html')
#
#
# @module_files.route('/upload_document/', methods=['GET', 'POST'])
# @login_required
# def upload_document():
#     id_dataset = 1
#     if current_user.admin is True:
#         context = core.get_dashboard_info()
#         data_directory = os.path.abspath(os.path.join(__file__, "../../../files/data"))
#         file = glob.glob(data_directory + '/**/' + '{}.xlsx'.format(id_dataset), recursive=True)
#         if request.method == 'POST':
#             file = request.files['file']
#             if file.filename == '':
#                 flash('Archivo no seleccionado')
#                 return redirect(url_for('files.upload_data'))
#             else:
#                 file.filename = '{}.xlsx'.format(id_dataset)
#                 filename = secure_filename(file.filename)
#                 file.save(os.path.join(UPLOAD_DATA_FOLDER, filename))
#                 return redirect(url_for('admin.datasets'))
#         return render_template('files/upload_dataset.html', **context, file=file)
#     else:
#         return redirect(url_for('catalogue.catalogue_topics'))

project/web_app/templates/core/layout.html
<!DOCTYPE html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Planes y Tarifas - POST[data]</title>
    {% endif %}
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keywords" content=""/>

    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <link rel="apple-touch-icon" href="../static/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../static/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../static/img/apple-touch-icon-114x114.png">

    <!-- Bootstrap
    ================================================== -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- Fonts
    ================================================== -->
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <!-- Custom Stylesheets
    ================================================== -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/core/base.css') }}">
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/landing/style.css') }}">-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/landing/prettyPhoto.css') }}">

    <!-- Custom Javascript
    ================================================== -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js" crossorigin="anonymous"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <style> html { scroll-behavior: smooth; } </style>

</head>

<body>
{% include "core/navbar.html" %}
<br>
<br>
<br>
<br>
<br>
<br>
{% block create %}{% endblock %}
{% block projects_cards %}{% endblock %}
{% block projects_matrix %}{% endblock %}
{% block projects_table %}{% endblock %}
{% block upload_files %}{% endblock %}
{% block comparation_table %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.bundle.js"></script>
</html>

project/web_app/templates/core/navbar.html
{% block navbar %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="">
            <img src="{{ url_for('static', filename='img/logo.svg') }}" width="" height="50" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Proyectos
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Proyectos</b></span>
                                <a class="dropdown-item" href="{{ url_for('projects.create_project') }}">Crear
                                    Proyecto</a>
                                <a class="dropdown-item" href="{{ url_for('projects.cards') }}">Listado</a>
                                <a class="dropdown-item" href="{{ url_for('projects.table') }}">Tabla de Proyectos</a>
                                <a class="dropdown-item" href="{{ url_for('projects.matrix') }}">Matriz Estratégica</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Buscador
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Buscar</b></span>
                                <a class="dropdown-item" href="">Comentarios</a>
                                <a class="dropdown-item" href="">Lecciones Aprendidas</a>
                                <a class="dropdown-item" href="#">Riesgos</a>
                                <a class="dropdown-item" href="{{ url_for('projects.faqs') }}">FAQs</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu3"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Administración
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Administración</b></span>
                                <a class="dropdown-item" href="">Dar Permisos</a>
                                <a class="dropdown-item" href="">Ingresar Funcionarios</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu5"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Analítica
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Tipos de Analítica</b></span>
                                <a class="dropdown-item" href="{{ url_for('projects.knowledge_graph') }}">Relaciones</a>
                                <a class="dropdown-item" href="{{ url_for('files.upload') }}">Comparar Documentos</a>
                                <a class="dropdown-item" href="">Personal Sugerido</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}